name: "trimmomatic se"
description: Trim single-end reads with Trimmomatic and (de)compress with pigz.
url: http://www.usadellab.org/cms/?page=trimmomatic
authors:
  - Johannes Köster
  - Jorge Langa
input:
  - fastq(gz) file(s)
output:
  - trimmed fastq file(s)
  - failed reads (optional)
params:
  - trimmer: trimming steps
  - extra: additional program arguments
