name: autobump

on:
  schedule:
    - cron: "0 0 * * 5"
  pull_request:
    branches:
      - "*"

jobs:
  autobump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.SNAKEDEPLOY_BOT_APP_ID }}
          private_key: ${{ secrets.SNAKEDEPLOY_BOT_PRIVATE_KEY }}

      # TODO restore old yml after debugging
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: snakedeploy
          channels: "conda-forge, bioconda"
          miniforge-variant: Mambaforge
          miniforge-version: latest

      - name: autobump
        shell: bash -el {0}
        run: |
          mamba install --only-deps snakedeploy
          pip install snakedeploy
          snakedeploy --verbose update-conda-envs */*/environment.yaml */*/*/environment.yaml --warn-on-error --entity-regex '(?P<entity>.+)/environment.yaml'

      # - name: Update conda envs
      #   uses: snakemake/snakedeploy-github-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      #   with:
      #     subcommand: update-conda-envs
      #     args: "*/*/environment.yaml */*/*/environment.yaml --warn-on-error --entity-regex '(?P<entity>.+)/environment.yaml'"
